services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taskmanager
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"

  postgres_test:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taskmanager
      POSTGRES_DB: taskmanager_test
    ports:
      - "5433:5432"
